#!/usr/bin/env bash
set -euo pipefail
set -x

if [ "${DEBUG_ENTRYPOINT:-}" == "1" ]; then
    echo "DEBUG_ENTRYPOINT set. Sleeping forever..."
    exec tail -f /dev/null
fi

# Load secrets if present (for runtime mounting mechanism)
if [ -f /mw-config/secrets.env ]; then
  echo "[entrypoint] Loading secrets from /mw-config/secrets.env"
  # Export variables from the file
  set -a
  source /mw-config/secrets.env
  set +a
fi

# Handle Short URLs
# We use root-based install, so we just need rewrites for /wiki
SCRIPT_PATH="${MW_SCRIPT_PATH:-}" # Default to empty (root)

echo "[entrypoint] Configuring Apache Rewrites"
# Ensure mod_rewrite is enabled
if [ -x "$(command -v a2enmod)" ]; then a2enmod rewrite; fi

{
    echo "# Generated by Labki Entrypoint"
    echo "RewriteEngine On"
    echo "RewriteBase /"
    echo "Options +FollowSymLinks"
    
    # Short URL Rules
    echo "RewriteRule ^/?wiki$ index.php [L]"
    echo "RewriteRule ^/?wiki/(.*)$ index.php [L]"
} > /var/www/html/.htaccess

# 1. Wait for Database
/opt/labki/scripts/wait-for-db.sh

# 2. Ensure LocalSettings.php exists
# If it's missing (fresh volume or first run), we write the loader.
if [ ! -f /var/www/html/LocalSettings.php ]; then
    echo "[entrypoint] Writing LocalSettings.php loader..."
    cat > /var/www/html/LocalSettings.php <<'PHP'
<?php
// Auto-generated by Labki Platform Entrypoint
// Do not edit this file. Edit mw-config/LocalSettings.user.php instead.
require_once '/opt/labki/mediawiki/bootstrap.php';
PHP
fi

# 3. Check if installed (Are tables present?)
# We use a simple query to check for the 'user' table (or 'page' or 'site_stats').
DB_HOST="${MW_DB_HOST:-db}"
DB_USER="${MW_DB_USER:-labki}"
DB_PASS="${MW_DB_PASSWORD:-labki_pass}"
DB_NAME="${MW_DB_NAME:-labki}"

echo "[entrypoint] Checking installation status..."

TABLE_COUNT=$(MYSQL_PWD="$DB_PASS" mysql --ssl=0 --protocol=TCP -h "$DB_HOST" -u "$DB_USER" -N -e \
    "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='$DB_NAME' AND table_name='user';" 2>/dev/null || echo "0")

if [ "$TABLE_COUNT" -eq "0" ]; then
    echo "[entrypoint] MediaWiki not found in DB. Installing..."
    /opt/labki/scripts/install-mediawiki.sh
else
    echo "[entrypoint] MediaWiki tables found."
fi

# 4. Run Updates
# This ensures schema changes are applied on upgrade.
# We skip this if we just installed, but running it is harmless idempotent.
echo "[entrypoint] Running database updates..."
php /var/www/html/maintenance/update.php --quick

# 5. Start CMD
echo "[entrypoint] Starting process: $@"
exec "$@"
