#!/usr/bin/env bash
set -euo pipefail
set -x

if [ "${DEBUG_ENTRYPOINT:-}" == "1" ]; then
    echo "DEBUG_ENTRYPOINT set. Sleeping forever..."
    exec tail -f /dev/null
fi

# Load secrets if present
if [ -f /mw-config/secrets.env ]; then
  echo "[entrypoint] Loading secrets from /mw-config/secrets.env"
  set -a
  source /mw-config/secrets.env
  set +a
fi

# Configure Short URL rewrites
echo "[entrypoint] Configuring Apache Rewrites"
if [ -x "$(command -v a2enmod)" ]; then a2enmod rewrite; fi

{
    echo "# Generated by Labki Entrypoint"
    echo "RewriteEngine On"
    echo "RewriteBase /"
    echo "Options +FollowSymLinks"
    echo "RewriteRule ^/?wiki$ index.php [L]"
    echo "RewriteRule ^/?wiki/(.*)$ index.php [L]"
} > /var/www/html/.htaccess

# Ensure upload directory is writable by the web server
echo "[entrypoint] Fixing images directory permissions..."
chown -R www-data:www-data /var/www/html/images 2>/dev/null || true

# Wait for Database
/opt/labki/scripts/wait-for-db.sh

# Ensure LocalSettings.php loader exists
if [ ! -f /var/www/html/LocalSettings.php ]; then
    echo "[entrypoint] Writing LocalSettings.php loader..."
    cat > /var/www/html/LocalSettings.php <<'PHP'
<?php
// Auto-generated by Labki Platform Entrypoint
// Do not edit this file. Edit mw-config/LocalSettings.user.php instead.
require_once '/opt/labki/mediawiki/bootstrap.php';
PHP
fi

# Check if MediaWiki tables exist in the database
DB_HOST="${MW_DB_HOST:-db}"
DB_USER="${MW_DB_USER:-labki}"
DB_PASS="${MW_DB_PASSWORD:-labki_pass}"
DB_NAME="${MW_DB_NAME:-labki}"

echo "[entrypoint] Checking installation status..."

TABLE_COUNT=$(MYSQL_PWD="$DB_PASS" mysql --ssl=0 --protocol=TCP -h "$DB_HOST" -u "$DB_USER" -N -e \
    "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='$DB_NAME' AND table_name='user';" 2>/dev/null || echo "0")

if [ "$TABLE_COUNT" -eq "0" ]; then
    echo "[entrypoint] MediaWiki not found in DB. Installing..."
    /opt/labki/scripts/install-mediawiki.sh
else
    echo "[entrypoint] MediaWiki tables found."
fi

# Run schema updates (idempotent)
echo "[entrypoint] Running database updates..."
php /var/www/html/maintenance/update.php --quick

# Start CMD
echo "[entrypoint] Starting process: $@"
exec "$@"
